<a href="https://colab.research.google.com/github/dhkdsns20/AI-Basic/blob/main/%EC%86%90%EA%B8%80%EC%94%A8%20%EC%9D%B8%EC%8B%9D.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 1) Solve the Prob. 1 from the attached file.

###(10 points) 간단한 3 층 신경망에서 W1은 2 × 3, b1은 1 × 3, W2는 3 × 2, b2는 1 × 2, W3 는 2 × 2, b3는 1 × 2 의 크기를 갖는다. 이 신경망을 본인의 nickname의 이름을 갖는 dictionary로 정의하고 6개의 변수의 값은 랜덤 함수를 이용하여 발생시킨다.




### (a) 정의된 dictionary 변수를 pickle의 함수를 이용하여 저장하시오

In [13]:
import numpy as np
import pickle

# ===============================
# 신경망 함수 정의
# ===============================

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def identity_function(x):
    return x

def forward(network, x):
    W1, W2, W3 = network['W1'], network['W2'], network['W3']
    b1, b2, b3 = network['b1'], network['b2'], network['b3']

    a1 = np.dot(x, W1) + b1
    z1 = sigmoid(a1)

    a2 = np.dot(z1, W2) + b2
    z2 = sigmoid(a2)

    a3 = np.dot(z2, W3) + b3
    y = identity_function(a3)

    return y

In [12]:


# 랜덤으로 파라미터 생성
scale = np.sqrt(0.1)

W1 = np.random.randn(2, 3) * scale
b1 = np.random.randn(1, 3) * scale

W2 = np.random.randn(3, 2) * scale
b2 = np.random.randn(1, 2) * scale

W3 = np.random.randn(2, 2) * scale
b3 = np.random.randn(1, 2) * scale

# sangwoo dictionary에 저장
sangwoo = {                            # 딕셔너리는 key , value 형태
    'W1': W1, 'b1': b1,
    'W2': W2, 'b2': b2,
    'W3': W3, 'b3': b3
}

# pickle을 이용해 파일로 저장
with open('sangwoo.pkl', 'wb') as f:   # 'wb'
                                       # 'w'는 쓰기모드
                                       # 'b'는 바이너리 모드 (pickle은 이지 데이터이므로 반드시 'b'사용)

                                       #  with
                                       #  파일을 열고 사용한 뒤 자동으로 닫아줌

                                       # as f : 이 파일 객체를 f라는 이름으로 사용
    pickle.dump(sangwoo, f)
    # pickle.dump() Python객체를 파일에 저장하는 함수.
    # sangwoo : 저장할 객체
    # f : 파일객체 (sangwoo.pkl)



### (b) 위의 dictionary 변수를 메모리에서 삭제하고 pickle 함수를 이용하여 다시 불러와 print하시오.

In [14]:
# ===============================
# (2) 메모리 삭제 후 다시 불러오기
# ===============================


import pickle

# sangwoo 딕셔너리 메모리에서 삭제
del sangwoo                            # del 명령어

# pickle 파일에서 다시 불러오기
with open('sangwoo.pkl', 'rb') as f:   # r : read모드
    sangwoo = pickle.load(f)           # pickle.load() : sangwoo.pkl을 불러옴

# 불러온 내용 출력
print("불러온 sangwoo 딕셔너리:")      # .items()로 key, value를 반복(iterate)
for key, value in sangwoo.items():     # sangwoo가 딕셔너리 형태이므로 key,value
    print(f"{key}:\n{value}\n")


불러온 sangwoo 딕셔너리:
W1:
[[ 0.17681539  0.14262558  0.27966331]
 [-0.03721515  0.06638266  0.34201209]]

b1:
[[ 0.36417479 -0.22939614  0.00736361]]

W2:
[[ 0.57718622  0.3146756 ]
 [ 0.32993822  0.24286372]
 [-0.01503647  0.19320682]]

b2:
[[0.19035105 0.04055933]]

W3:
[[0.12258136 0.40125189]
 [0.11879685 0.57447003]]

b3:
[[0.07386619 0.46115148]]



In [15]:
# ===============================
# (3) 입력값을 통한 forward 계산
# ===============================

x = np.array([1.0, 0.5])  # 입력값 정의
y = forward(sangwoo, x)   # forward 함수 실행

print("신경망 출력값 y:")
print(y)

신경망 출력값 y:
[[0.22911725 1.08376423]]


## 2) Make your own handwritten number (본인 학번의 마지막 숫자로 인식시킬 것)

and check that the simple Section 3.6 (sample_weight.pkl)  can tell the number of your own.

* mnist.pkl 을 4주 강의자료에 업로드했습니다. (mnist data를 인터넷에서 더 이상 제공하지 않을 수 있습니다.)

   mnist를 working directory에 다운하여 숙제를 하면 됩니다

### 2) Make your own handwritten number

In [96]:
# 학번 : 2020037087

from PIL import Image
import numpy as np

# 이미지 열기 (28x28 흑백으로 resize)
img = Image.open('7번(3).png').convert('L').resize((28, 28)) # .convert('L') : 이미지를 흑백으로 변환하라.
img_np = np.array(img)

# MNIST와 동일하게 흰색 배경이 0, 글자가 큰 값이 되게 반전
img_np = 255 - img_np

# 1차원으로 펴고 정규화
img_np = img_np.flatten() / 255.0


In [97]:
import pickle

# 모델 로드
with open("sample_weight.pkl", 'rb') as f:
    network = pickle.load(f)


In [98]:
def predict(network, x):
    W1, W2, W3 = network['W1'], network['W2'], network['W3']
    b1, b2, b3 = network['b1'], network['b2'], network['b3']

    a1 = np.dot(x, W1) + b1
    z1 = sigmoid(a1)
    a2 = np.dot(z1, W2) + b2
    z2 = sigmoid(a2)
    a3 = np.dot(z2, W3) + b3
    y = softmax(a3)

    return y


In [99]:
y = predict(network, img_np)
print("예측 결과:", np.argmax(y))


예측 결과: 7


### MNIST 데이터셋

In [27]:
# import sys, os
# sys.path.append(os.pardir)  # 부모 디렉터리의 파일을 가져올 수 있도록 설정
from mnist import load_mnist

In [28]:
(x_train, t_train), (x_test, t_test) = \
    load_mnist(flatten=True, normalize=False) # 세번째 인수는 원-핫 인코딩
                                              # one_hot_label = True : 정답만 1
                                              # one_hot_label = False : 정답은 '2', '7' 처럼 숫자 형태



In [29]:
# 각 데이터의 형상 출력
print(x_train.shape)   # 훈련 이미지
print(t_train.shape)   # 훈련 레이블
print(x_test.shape)    # 시험 이미지
print(t_test.shape)    # 시험 레이블

(60000, 784)
(60000,)
(10000, 784)
(10000,)


In [30]:
img = x_train[0]
label = t_train[0]
print(label)

5


In [31]:
print(img.shape)          # (784,)
img = img.reshape(28,28)  # 원래 이미지의 모양으로 변형
print(img.shape)          # (28,28)

(784,)
(28, 28)


In [47]:
# 넘파이로 저장된 이미지 데이터 -> PIL용 데이터 객체로 변환 : Image.fromarray()가 수행
from PIL import Image

def img_show(img):
  pil_img = Image.fromarray(np.uint8(img))
  pil_img.show()

img_show(img)

```python
    # colab에서의 코드
    import matplotlib.pyplot as plt
    import numpy as np

    def img_show(img):
        if img.ndim == 1:
            img = img.reshape(28, 28)  # 1차원인 경우 28x28로 변경
        if img.max() <= 1.0:
            img = img * 255  # 0~1 범위면 0~255로 변환
        img = np.uint8(img)
        
        plt.imshow(img, cmap='gray')
        plt.axis('off')
        plt.show()


    img = x_train[0]  # 예: MNIST 첫 번째 이미지
    img_show(img)
```

### 3.6.2 신경망의 추론처리

In [51]:
import pickle
import numpy as np
from common.functions import sigmoid, softmax

def get_data():
    (x_train, t_train), (x_test, t_test) = \
        load_mnist(normalize=True, flatten=True, one_hot_label=False)
    return x_test, t_test

def init_network():
    with open("sample_weight.pkl", "rb") as f:
        network = pickle.load(f)
    return network

def predict(network, x):
    W1, W2, W3 = network['W1'], network['W2'], network['W3']
    b1, b2, b3 = network['b1'], network['b2'], network['b3']

    a1 = np.dot(x, W1) + b1
    z1 = sigmoid(a1)
    a2 = np.dot(z1, W2) + b2
    z2 = sigmoid(a2)
    a3 = np.dot(z2, W3) + b3
    y = softmax(a3)
    return y

In [ ]:
x, t = get_data()
network = init_network()

accuracy_cnt = 0
for i in range(len(x)):
    y = predict(network, x[i])
    p = np.argmax(y)
    if p == t[i]:
        accuracy_cnt +=1

print("Accuracy:" + str(float(accuracy_cnt) / len(x)))

### 3.6.3 배치 처리

In [52]:
x, t = get_data()
network = init_network()

batch_size = 100 # 배치 크기
accuracy_cnt = 0

for i in range(0, len(x), batch_size):       # len(x) = 10000
    x_batch = x[i:i+batch_size]              # i = 0,100,200... / x[0:100],x[100:200],...
    y_batch = predict(network, x_batch)
    p = np.argmax(y_batch, axis=1)
    accuracy_cnt += np.sum(p == t[i:i+batch_size])

print("Accuracy:" + str(float(accuracy_cnt) / len(x)))

Accuracy:0.9352
